version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: preact
    versions:
    - 10.5.12
  - dependency-name: sirv-cli
    versions:
    - 1.0.11
